module.exports = {
	DEXClientContract: {
		abi: {
			"ABI version": 2,
			header: ["pubkey", "time", "expire"],
			functions: [
				{
					name: "constructor",
					inputs: [{name: "ownerAddr", type: "address"}],
					outputs: [],
				},
				{
					name: "connectPair",
					inputs: [{name: "pairAddr", type: "address"}],
					outputs: [{name: "statusConnection", type: "bool"}],
				},
				{
					name: "setPair",
					inputs: [
						{name: "arg0", type: "address"},
						{name: "arg1", type: "address"},
						{
							name: "arg2",
							type: "address",
						},
						{name: "arg3", type: "address"},
						{name: "arg4", type: "address"},
					],
					outputs: [],
				},
				{
					name: "getConnectorAddress",
					inputs: [
						{name: "_answer_id", type: "uint32"},
						{name: "connectorSoArg", type: "uint256"},
					],
					outputs: [{name: "value0", type: "address"}],
				},
				{
					name: "connectRoot",
					inputs: [
						{name: "root", type: "address"},
						{
							name: "souint",
							type: "uint256",
						},
						{name: "gramsToConnector", type: "uint128"},
						{name: "gramsToRoot", type: "uint128"},
					],
					outputs: [{name: "statusConnected", type: "bool"}],
				},
				{
					name: "connectCallback",
					inputs: [{name: "wallet", type: "address"}],
					outputs: [],
				},
				{
					name: "getAllDataPreparation",
					inputs: [],
					outputs: [
						{name: "pairKeysR", type: "address[]"},
						{name: "rootKeysR", type: "address[]"},
					],
				},
				{
					name: "processSwapA",
					inputs: [
						{name: "pairAddr", type: "address"},
						{
							name: "qtyA",
							type: "uint128",
						},
						{name: "minQtyB", type: "uint128"},
						{name: "maxQtyB", type: "uint128"},
					],
					outputs: [{name: "processSwapStatus", type: "bool"}],
				},
				{
					name: "processSwapB",
					inputs: [
						{name: "pairAddr", type: "address"},
						{
							name: "qtyB",
							type: "uint128",
						},
						{name: "minQtyA", type: "uint128"},
						{name: "maxQtyA", type: "uint128"},
					],
					outputs: [{name: "processSwapStatus", type: "bool"}],
				},
				{
					name: "processLiquidity",
					inputs: [
						{name: "pairAddr", type: "address"},
						{
							name: "qtyA",
							type: "uint128",
						},
						{name: "qtyB", type: "uint128"},
					],
					outputs: [{name: "processLiquidityStatus", type: "bool"}],
				},
				{
					name: "returnLiquidity",
					inputs: [
						{name: "pairAddr", type: "address"},
						{name: "tokens", type: "uint128"},
					],
					outputs: [{name: "returnLiquidityStatus", type: "bool"}],
				},
				{
					name: "tokensReceivedCallback",
					inputs: [
						{name: "token_wallet", type: "address"},
						{
							name: "token_root",
							type: "address",
						},
						{name: "amount", type: "uint128"},
						{
							name: "sender_public_key",
							type: "uint256",
						},
						{name: "sender_address", type: "address"},
						{
							name: "sender_wallet",
							type: "address",
						},
						{name: "original_gas_to", type: "address"},
						{
							name: "updated_balance",
							type: "uint128",
						},
						{name: "payload", type: "cell"},
					],
					outputs: [],
				},
				{
					name: "createNewPair",
					inputs: [
						{name: "root0", type: "address"},
						{
							name: "root1",
							type: "address",
						},
						{name: "pairSoArg", type: "uint256"},
						{
							name: "connectorSoArg0",
							type: "uint256",
						},
						{name: "connectorSoArg1", type: "uint256"},
						{
							name: "rootSoArg",
							type: "uint256",
						},
						{name: "rootName", type: "bytes"},
						{
							name: "rootSymbol",
							type: "bytes",
						},
						{name: "rootDecimals", type: "uint8"},
						{
							name: "grammsForPair",
							type: "uint128",
						},
						{name: "grammsForRoot", type: "uint128"},
						{
							name: "grammsForConnector",
							type: "uint128",
						},
						{name: "grammsForWallet", type: "uint128"},
						{name: "grammsTotal", type: "uint128"},
					],
					outputs: [],
				},
				{
					name: "getPairData",
					inputs: [{name: "pairAddr", type: "address"}],
					outputs: [
						{name: "pairStatus", type: "bool"},
						{
							name: "pairRootA",
							type: "address",
						},
						{name: "pairWalletA", type: "address"},
						{
							name: "pairRootB",
							type: "address",
						},
						{name: "pairWalletB", type: "address"},
						{
							name: "pairRootAB",
							type: "address",
						},
						{name: "curPair", type: "address"},
					],
				},
				{
					name: "sendTokens",
					inputs: [
						{name: "tokenRoot", type: "address"},
						{
							name: "to",
							type: "address",
						},
						{name: "tokens", type: "uint128"},
						{name: "grams", type: "uint128"},
					],
					outputs: [{name: "sendTokenStatus", type: "bool"}],
				},
				{
					name: "sendTransaction",
					inputs: [
						{name: "dest", type: "address"},
						{name: "value", type: "uint128"},
						{
							name: "bounce",
							type: "bool",
						},
						{name: "flags", type: "uint8"},
						{name: "payload", type: "cell"},
					],
					outputs: [],
				},
				{
					name: "deployLockStakeSafeCallback",
					inputs: [
						{name: "lockStakeSafe", type: "address"},
						{
							name: "nftKey",
							type: "address",
						},
						{name: "amount", type: "uint128"},
						{name: "period", type: "uint256"},
					],
					outputs: [],
				},
				{
					name: "transferOwnershipCallback",
					inputs: [
						{name: "addrFrom", type: "address"},
						{name: "addrTo", type: "address"},
					],
					outputs: [],
				},
				{
					name: "processLiquidityCallback",
					inputs: [
						{name: "walletA", type: "address"},
						{
							name: "amountA",
							type: "uint128",
						},
						{name: "provideA", type: "uint128"},
						{
							name: "unusedReturnA",
							type: "uint128",
						},
						{name: "walletB", type: "address"},
						{name: "amountB", type: "uint128"},
						{
							name: "provideB",
							type: "uint128",
						},
						{name: "unusedReturnB", type: "uint128"},
						{
							name: "walletAB",
							type: "address",
						},
						{name: "mintAB", type: "uint128"},
					],
					outputs: [],
				},
				{
					name: "returnLiquidityCallback",
					inputs: [
						{name: "walletAB", type: "address"},
						{
							name: "burnAB",
							type: "uint128",
						},
						{name: "walletA", type: "address"},
						{name: "returnA", type: "uint128"},
						{
							name: "walletB",
							type: "address",
						},
						{name: "returnB", type: "uint128"},
					],
					outputs: [],
				},
				{
					name: "limitOrderCallback",
					inputs: [
						{name: "status", type: "uint8"},
						{
							name: "addrOrder",
							type: "address",
						},
						{name: "addrOwner", type: "address"},
						{
							name: "addrPair",
							type: "address",
						},
						{name: "directionPair", type: "uint8"},
						{name: "price", type: "uint128"},
						{
							name: "amount",
							type: "uint128",
						},
						{name: "walletOwnerFrom", type: "address"},
						{name: "walletOwnerTo", type: "address"},
					],
					outputs: [],
				},
				{
					name: "makeLimitOrderA",
					inputs: [
						{name: "routerWalletA", type: "address"},
						{
							name: "pairAddr",
							type: "address",
						},
						{name: "qtyA", type: "uint128"},
						{name: "priceA", type: "uint128"},
						{
							name: "souint",
							type: "uint256",
						},
					],
					outputs: [{name: "makeLimitOrderStatus", type: "bool"}],
				},
				{
					name: "makeLimitOrderB",
					inputs: [
						{name: "routerWalletB", type: "address"},
						{
							name: "pairAddr",
							type: "address",
						},
						{name: "qtyB", type: "uint128"},
						{name: "priceB", type: "uint128"},
						{
							name: "souint",
							type: "uint256",
						},
					],
					outputs: [{name: "makeLimitOrderStatus", type: "bool"}],
				},
				{
					name: "transferLimitOrder",
					inputs: [
						{name: "limitOrder", type: "address"},
						{
							name: "addrNewOwner",
							type: "address",
						},
						{name: "walletNewOwnerFrom", type: "address"},
						{name: "walletNewOwnerTo", type: "address"},
					],
					outputs: [{name: "transferLimitOrderStatus", type: "bool"}],
				},
				{
					name: "changeLimitOrderPrice",
					inputs: [
						{name: "limitOrder", type: "address"},
						{name: "newPrice", type: "uint128"},
					],
					outputs: [{name: "changePriceStatus", type: "bool"}],
				},
				{
					name: "cancelLimitOrder",
					inputs: [{name: "limitOrder", type: "address"}],
					outputs: [{name: "cancelOrderStatus", type: "bool"}],
				},
				{
					name: "takeLimitOrderA",
					inputs: [
						{name: "pairAddr", type: "address"},
						{
							name: "limitOrderA",
							type: "address",
						},
						{name: "routerWalletB", type: "address"},
						{name: "qtyB", type: "uint128"},
						{
							name: "priceB",
							type: "uint128",
						},
					],
					outputs: [{name: "takeLimitOrderStatus", type: "bool"}],
				},
				{
					name: "takeLimitOrderB",
					inputs: [
						{name: "pairAddr", type: "address"},
						{
							name: "limitOrderB",
							type: "address",
						},
						{name: "routerWalletA", type: "address"},
						{name: "qtyA", type: "uint128"},
						{
							name: "priceA",
							type: "uint128",
						},
					],
					outputs: [{name: "takeLimitOrderStatus", type: "bool"}],
				},
				{
					name: "rootDEX",
					inputs: [],
					outputs: [{name: "rootDEX", type: "address"}],
				},
				{
					name: "soUINT",
					inputs: [],
					outputs: [{name: "soUINT", type: "uint256"}],
				},
				{
					name: "codeDEXConnector",
					inputs: [],
					outputs: [{name: "codeDEXConnector", type: "cell"}],
				},
				{
					name: "owner",
					inputs: [],
					outputs: [{name: "owner", type: "address"}],
				},
				{
					name: "rootKeys",
					inputs: [],
					outputs: [{name: "rootKeys", type: "address[]"}],
				},
				{
					name: "rootWallet",
					inputs: [],
					outputs: [{name: "rootWallet", type: "map(address,address)"}],
				},
				{
					name: "rootConnector",
					inputs: [],
					outputs: [{name: "rootConnector", type: "map(address,address)"}],
				},
				{
					name: "souintLast",
					inputs: [],
					outputs: [{name: "souintLast", type: "uint256"}],
				},
				{
					name: "pc",
					inputs: [],
					outputs: [
						{
							components: [
								{name: "pcType", type: "uint8"},
								{name: "pcFrom", type: "address"},
							],
							name: "pc",
							type: "tuple",
						},
					],
				},
				{
					name: "pairs",
					inputs: [],
					outputs: [
						{
							components: [
								{name: "status", type: "bool"},
								{
									name: "rootA",
									type: "address",
								},
								{name: "walletA", type: "address"},
								{name: "rootB", type: "address"},
								{
									name: "walletB",
									type: "address",
								},
								{name: "rootAB", type: "address"},
							],
							name: "pairs",
							type: "map(address,tuple)",
						},
					],
				},
				{
					name: "pairKeys",
					inputs: [],
					outputs: [{name: "pairKeys", type: "address[]"}],
				},
			],
			data: [
				{key: 1, name: "rootDEX", type: "address"},
				{
					key: 2,
					name: "soUINT",
					type: "uint256",
				},
				{key: 3, name: "codeDEXConnector", type: "cell"},
			],
			events: [],
		},
		tvc: "te6ccgECpAEAMDEAAgE0AwEBAcACAEPQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgBCSK7VMg4wMgwP/jAiDA/uMC8guhBgSjAQAFAv6NCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAT4aSHbPNMAAY4dgQIA1xgg+QEB0wABlNP/AwGTAvhC4iD4ZfkQ8qiV0wAB8nri0z8B+EMhufK0IPgjgQPoqIIIG3dAoLnytPhj0x8B+CO88rnTHwHbPPhHbvJ8RQcBaiLQ0wP6QDD4aak4APhEf29xggiYloBvcm1vc3BvdPhk3CHHANwh1w0f8rwh3QHbPPhHbvJ8BwM8IIIQNmc+qbvjAiCCEF4RYXG74wIgghBycMeDu+MCXiAIAiggghBtfd67u+MCIIIQcnDHg7vjAhkJAzwgghBwiI0fuuMCIIIQcQ2URrrjAiCCEHJwx4O64wIWEgoDsjD4Qm7jAPpBldTR0PpA39cNf5XU0dDTf9/XDX+V1NHQ03/f0ds8IY4oI9DTAfpAMDHIz4cgzo0EAAAAAAAAAAAAAAAADycMeDjPFsoAyXD7AJEw4uMAf/hnoAudA+pw+EUgbpIwcN74QrogjjYw+En4TY0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMcFsyCWMCD4TccF3jHf8uBm+CdvEIIQstBeALV/vvLgcfgAMHBTM/hUgQEL9AuOgI6A4iBvEfhQgQEL9AqZlwwCyo4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3/hRgQEL9AuOgI4ojQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEcHBvA+IhbxP4UIEBC/QKlQ0Cvo4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3/hRgQEL9AuOgI4ojQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEcHBvA+IibxAglQ4B6I5pMCJvEfhPgQEL9AogkTHeII5WMCJvE/hPgQEL9AogkTHeII5DMCJvFfhPgQEL9AogkTHeII4wMCJvEfhQgQEL9AogkTHeII4dMCJvE/hQgQEL9AogkTHeIJswIW8SIJQwIG8S3t7e3t7e3mwxMY6A3mwxDwP6I/hUgQEL9AuOgI6A4iBvEfhQgQEL9AqOJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN8hbxP4UIEBC/QKjiSNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATfyCByciZvFfhPgQEL9AqZlxAB/o4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3/goclUEywfOzst/y38xIMnIIHJyKG8V+E+BAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3/goclUEywfOzst/y38xIMlUcpYRANRvEsjPkTr7/UbOy3/MyVRxl28UyM+ROvv9Rs7Lf8zJJ8jPhYjOjQSRZaC8AAAAAAAAAAAAAAAAAADAzxYizxTJcPsAJsjPhYjOjQSRZaC8AAAAAAAAAAAAAAAAAADAzxYhzxTJcPsAXwp/A4ow+EJu4wD6QZXU0dD6QN/R2zwhjigj0NMB+kAwMcjPhyDOjQQAAAAAAAAAAAAAAAAPENlEaM8WygDJcPsAkTDi2zx/+GegE50B1nD4RSBukjBw3vhCuiCONjD4SfhNjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAExwWzIJYwIPhNxwXeMd/y4Gb4J28QghBZaC8AvvLgbvgAMHAh+FSBAQv0CiCRMd6OgN8xFASwIfhUgQEL9AuOgI6A4nBvUCL4VCLbPMlZgQEL9BP4dCL4VW8iIaRVIIAg9BZvAvh1iCPIz4WIzo0EkWWgvAAAAAAAAAAAAAAAAAAAwM8WIc8UyXD7AF8Df5mXKRUACGLFrusDnjD4Qm7jAPpBldTR0PpA39cNf5XU0dDTf9/R2zwhjigj0NMB+kAwMcjPhyDOjQQAAAAAAAAAAAAAAAAPCIjR+M8WygDJcPsAkTDi4wB/+GegF50B2HD4RSBukjBw3vhCuiCONjD4SfhNjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAExwWzIJYwIPhNxwXeMd/y4Gb4J28QghBZaC8AvvLgbvgAMHAhyM+QYLq3sst/ySPIz4WIzhgARI0EkWWgvAAAAAAAAAAAAAAAAAAAwM8WIc8UyXD7AFt/bCEEUCCCEF7tOXa64wIgghBfC8/euuMCIIIQY1Nmp7rjAiCCEG193ru64wIeHRwaA0Aw+EJu4wD6QZXU0dD6QN/6QZXU0dD6QN/R2zzbPH/4Z6AbnQAs+CdvEGim/mChtX9y+wJbePhJbwL4cwFSMNHbPPhPIY4cjQRwAAAAAAAAAAAAAAAAONTZqeDIzvQAyXD7AN5/+GegAVAw0ds8+E0hjhuNBHAAAAAAAAAAAAAAAAA3wvP3oMjOzslw+wDef/hnoAO2MPhCbuMA0wf6QZXU0dD6QN/6QZXU0dD6QN/6QZXU0dD6QN/XDQeV1NHQ0wff1w1/ldTR0NN/39cNf5XU0dDTf9/6QZXU0dD6QN/6QZXU0dD6QN/R2zzbPH/4Z6AfnQAs+CdvEGim/mChtX9y+wJfCPhJbwL4cwRQIIIQRvJqSrvjAiCCEE3+ali74wIgghBTw/o6u+MCIIIQXhFhcbvjAkk+KiEEUCCCEFT9xUi64wIgghBZQR+5uuMCIIIQWc+WpLrjAiCCEF4RYXG64wInJSQiA44w+EJu4wD6QZXU0dD6QN/XDX+V1NHQ03/f+kGV1NHQ+kDf1w1/ldTR0NN/3/pBldTR0PpA39cNf5XU0dDTf9/R2zzbPH/4Z6AjnQBO+En4VIEBC/QKIJEx3vLgbPgnbxBopv5gobV/cvsCXwZ6+ElvAvhzAVIw0ds8+FIhjhyNBHAAAAAAAAAAAAAAAAA2c+WpIMjOy//JcPsA3n/4Z6ADtDD4Qm7jAPpBldTR0PpA3/pBldTR0PpA39cNf5XU0dDTf9/XDf+V1NHQ0//f+kGV1NHQ+kDf+kGV1NHQ+kDf+kGV1NHQ+kDf1w1/ldTR0NN/39TR2zzbPH/4Z6AmnQAg+CdvEGim/mChtX9y+wJfCQN2MPhCbuMA+kGV1NHQ+kDf+kGV1NHQ+kDf+kGV1NHQ+kDf+kGV1NHQ+kDf+kGV1NHQ+kDf0ds82zx/+GegKJ0DoPhJ+FSBAQv0CiCRMd7y4Gz4J28QaKb+YKG1f3L7AvhJIPhUgQEL9AuOgI6A4n9vUCZvUSVvUiRvUyNvVCJvVSH4VCLbPMlZgQEL9BP4dF8HmZcpADRvJl5AyMoAzlUwyM5VIMjOWcjOAcjOzc3NzQRQIIIQUGkGo7rjAiCCEFF/bKW64wIgghBR72U/uuMCIIIQU8P6OrrjAjkyMSsD1jD4Qm7jAPpBldTR0PpA3/pBldTR0PpA3/pBldTR0PpA39cNf5XU0dDTf9/XDX+V1NHQ03/f0ds8IY4oI9DTAfpAMDHIz4cgzo0EAAAAAAAAAAAAAAAADTw/o6jPFsoAyXD7AJEw4uMAf/hnoCydA+Zw+EUgbpIwcN74QrogjjYw+En4TY0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMcFsyCWMCD4TccF3jHf8uBm+CdvEIIQWWgvAL7y4G74ADBwU1X4VIEBC/QLjoCOgOIgbxH4UIEBC/QKmZctAsqOJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/4UYEBC/QLjoCOKI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHBwbwPiIW8T+FCBAQv0CpUuAr6OJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/4UYEBC/QLjoCOKI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHBwbwPiIm8QIJUvAcKOVjAibxH4T4EBC/QKIJEx3iCOQzAibxP4T4EBC/QKIJEx3iCOMDAibxH4UIEBC/QKIJEx3iCOHTAibxP4UIEBC/QKIJEx3iCbMCFvEiCUMCBvEt7e3t7e3mwxMY6A3mxRMAP+JfhUgQEL9AuOgI6A4iBvE/hQgQEL9AqOJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/IIF8mJW8R+E+BAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3yt2VQTLB87Oy3/Lf5mXOAFQMNHbPPhKIY4bjQRwAAAAAAAAAAAAAAAANHvZT+DIzs7JcPsA3n/4Z6AD1jD4Qm7jAPpBldTR0PpA3/pBldTR0PpA3/pBldTR0PpA39cNf5XU0dDTf9/XDX+V1NHQ03/f0ds8IY4oI9DTAfpAMDHIz4cgzo0EAAAAAAAAAAAAAAAADRf2yljPFsoAyXD7AJEw4uMAf/hnoDOdA+Zw+EUgbpIwcN74QrogjjYw+En4TY0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMcFsyCWMCD4TccF3jHf8uBm+CdvEIIQWWgvAL7y4G74ADBwU1X4VIEBC/QLjoCOgOIgbxH4UIEBC/QKmZc0AsqOJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/4UYEBC/QLjoCOKI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHBwbwPiIW8T+FCBAQv0CpU1Ar6OJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/4UYEBC/QLjoCOKI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHBwbwPiIm8QIJU2AcKOVjAibxH4T4EBC/QKIJEx3iCOQzAibxP4T4EBC/QKIJEx3iCOMDAibxH4UIEBC/QKIJEx3iCOHTAibxP4UIEBC/QKIJEx3iCbMCFvEiCUMCBvEt7e3t7e3mwxMY6A3mxRNwP+JfhUgQEL9AuOgI6A4iBvEfhQgQEL9AqOJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/IIF8mJW8T+E+BAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3yt3VQTLB87Oy3/Lf5mXOAByMSDJVHBnyM+ROvv9Rs7Lf8zJI8jPhYjOjQSRZaC8AAAAAAAAAAAAAAAAAADAzxYhzxTJcPsAXwZ/A8Qw+EJu4wD6QZXU0dD6QN/6QZXU0dD6QN/XDX+V1NHQ03/f1w1/ldTR0NN/39HbPCGOKCPQ0wH6QDAxyM+HIM6NBAAAAAAAAAAAAAAAAA0GkGo4zxbKAMlw+wCRMOLjAH/4Z6A6nQG8cPhFIG6SMHDe+EK6II42MPhJ+E2NCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATHBbMgljAg+E3HBd4x3/LgZvgnbxAivvLgcvgAMHAk+FCBAQv0CjsBpI4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE340IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMcFjoDfbEE8Af4k+FCBAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE38ggdHQp+E+BAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3/godFUEywfOzst/y38xIMlUcFbIz5E6+/1Gzst/PQA0zMlTU8jPhYjOAfoCcc8LaiHPFMlw+wBfBX8EUCCCEEdWVNy64wIgghBJhZe6uuMCIIIQTO5kbLrjAiCCEE3+ali64wJDQkA/AV4w0ds8+E4hjiKNBHAAAAAAAAAAAAAAAAAzf5qWIMjOAW8iAssf9ADJcPsA3n/4Z6ADbDD4Qm7jAPpBldTR0PpA39cNf5XU0dDTf9/XDACV1NHQ0gDf1w0HldTR0NMH39TR2zzjAH/4Z6BBnQDg+EUgbpIwcN74QrogjjYw+En4TY0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMcFsyCWMCD4TccF3jHf8uBm+CdvECS+8uBz+ABUc0LIz4WAygBzz0DOAfoCcc8LaiHPFMki+wBfBQFcMNHbPPhTIY4hjQRwAAAAAAAAAAAAAAAAMmFl7qDIzgFvIgLLB87JcPsA3n/4Z6ACxDD4Qm7jAPhG8nN/+Gb6QZXU0dD6QN/R+En4SscFjkP4J28QghA7msoAoLV/aKb+YKG1f3L7Al8g+G34KPhCyM+Q6BWtjsv/zgHIzs3J+ErIz4WIznHPC24hzxTJgQCA+wAwRUQB1o5i+ACNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQg+G34KPhCyM+Q6BWtjsv/zgHIzs3J+ErIz4WIzo0EkHc1lAAAAAAAAAAAAAAAAAAAwM8WIc8UyXD7ADDiMNs8f/hnnQIW7UTQ10nCAYqOgOKgRgL+cO1E0PQFcSGAQPQOjiSNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATf+GpyIYBA9A6T1wv/kXDi+GtzIYBA9A+OgN/4bI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABPhtcG1vAvhubfhvbUhHAJb4cG34cXD4cnCNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARvAvhzbfh0cG1vAvh1gED0DvK91wv/+GJw+GNw+GYBAoijBFAgghA8FwBhuuMCIIIQRDh4CrrjAiCCEEVETxq64wIgghBG8mpKuuMCWlNMSgPyMPhCbuMA0x/4RFhvdfhk1w3/ldTR0NP/39HbPCGOHyPQ0wH6QDAxyM+HIM5xzwthAcjPkxvJqSrOzclw+wCOM/hEIG8TIW8S+ElVAm8RyHLPQMoAc89AzgH6AvQAcc8LaQHI+ERvFc8LH87NyfhEbxT7AOLjAH/4Z6BLnQCW+ERwb3Jwb3GAQG90+GQgbfhCyMv/cFiAQPRDIcjL/3FYgED0Q/gocliAQPQWyPQAyfhMyM+EgPQA9ADPgcn5AMjPigBAy//J0DExA8Yw+EJu4wD6QZXU0dD6QN/XDX+V1NHQ03/f1w1/ldTR0NN/39cNf5XU0dDTf9/R2zwhjigj0NMB+kAwMcjPhyDOjQQAAAAAAAAAAAAAAAAMVETxqM8WygDJcPsAkTDi4wB/+GegTZ0D5nD4RSBukjBw3vhCuiCONjD4SfhNjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAExwWzIJYwIPhNxwXeMd/y4Gb4J28QghBZaC8AvvLgbvgAMHBTRPhUgQEL9AuOgI6A4iBvEfhQgQEL9AqZl04Cyo4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3/hRgQEL9AuOgI4ojQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEcHBvA+IhbxP4UIEBC/QKlU8Cvo4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3/hRgQEL9AuOgI4ojQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEcHBvA+IibxAglVABwo5WMCJvEfhPgQEL9AogkTHeII5DMCJvE/hPgQEL9AogkTHeII4wMCJvEfhQgQEL9AogkTHeII4dMCJvE/hQgQEL9AogkTHeIJswIW8SIJQwIG8S3t7e3t7ebDExjoDebEFRA/wk+FSBAQv0C46AjoDiIG8R+FCBAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE38hUcEUlbxP4T4EBC/QKjiSNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATf+ChxVQTLB87Oy3+Zl1IAest/MSDJVHBzbxLIz5E6+/1Gzst/zMkjyM+FiM6NBJFloLwAAAAAAAAAAAAAAAAAAMDPFiHPFMlw+wBfBn8DnjD4Qm7jAPpBldTR0PpA39cNf5XU0dDTf9/R2zwhjigj0NMB+kAwMcjPhyDOjQQAAAAAAAAAAAAAAAAMQ4eAqM8WygDJcPsAkTDi4wB/+GegVJ0D5nD4RSBukjBw3vhCuiCONjD4SfhNjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAExwWzIJYwIPhNxwXeMd/y4Gb4J28QghBZaC8AvvLgbvgAMHBTIvhUgQEL9AuOgI6A4iBvEfhQgQEL9AqZl1UCyo4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3/hRgQEL9AuOgI4ojQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEcHBvA+IhbxP4UIEBC/QKlVYCvo4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3/hRgQEL9AuOgI4ojQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEcHBvA+IibxAglVcB6I5pMCJvEfhPgQEL9AogkTHeII5WMCJvE/hPgQEL9AogkTHeII5DMCJvFfhPgQEL9AogkTHeII4wMCJvEfhQgQEL9AogkTHeII4dMCJvE/hQgQEL9AogkTHeIJswIW8SIJQwIG8S3t7e3t7e3mwxMY6A3mwhWAP+IvhUgQEL9AuOgI6A4sggc3MkbxP4T4EBC/QKjiSNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATfJW8R+E+BAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE33NVBMsHzs7Lf8t/MZmXWQDQIMkgXybIz5G0qjiOy3/OzMkjbxX4UIEBC/QKjiSNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATfyM+FiM6NBJFloLwAAAAAAAAAAAAAAAAAAMDPFiHPFMlw+wBfBX8DsjD4Qm7jAPpBldTR0PpA39HbPCeOOynQ0wH6QDAxyM+HIM5xzwthXlFVYMjPkvBcAYbKAM5VQMjOVTDIzlUgyM5ZyM4ByM7Nzc3Nzc3JcPsAkl8H4uMAf/hnoFudAdpwjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEXAP8jQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEJ/hUgQEL9AuOgI6A4iBvEDggmZddACxvETcgbxI2IG8TNSBvFDRvFTIwJmwXBFAgghAM46Diu+MCIIIQGIOlUrvjAiCCECxl2Q+74wIgghA2Zz6pu+MCiXxpXwRQIIIQLjVeOrrjAiCCEDKmhOG64wIgghAzNqVSuuMCIIIQNmc+qbrjAmNiYWABXjDR2zz4VSGOIo0EcAAAAAAAAAAAAAAAAC2Zz6pgyM4BbyICyx/0AMlw+wDef/hnoAFSMNHbPPhLIY4cjQRwAAAAAAAAAAAAAAAALM2pVKDIzsv/yXD7AN5/+GegAVAw0ds8+EwhjhuNBHAAAAAAAAAAAAAAAAAsqaE4YMjOzMlw+wDef/hnoAPYMPhCbuMA+kGV1NHQ+kDf+kGV1NHQ+kDf1w1/ldTR0NN/39cNf5XU0dDTf9/XDf+V1NHQ0//f0ds8IY4oI9DTAfpAMDHIz4cgzo0EAAAAAAAAAAAAAAAACuNV46jPFsoAyXD7AJEw4uMAf/hnoGSdA+Zw+EUgbpIwcN74QrogjjYw+En4TY0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMcFsyCWMCD4TccF3jHf8uBm+CdvEIIQWWgvAL7y4G74ADBwU0T4VIEBC/QLjoCOgOIgbxH4UIEBC/QKmZdlAsqOJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/4UYEBC/QLjoCOKI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHBwbwPiIW8T+FCBAQv0CpVmAr6OJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/4UYEBC/QLjoCOKI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHBwbwPiIm8QIJVnAcKOVjAibxH4T4EBC/QKIJEx3iCOQzAibxP4T4EBC/QKIJEx3iCOMDAibxH4UIEBC/QKIJEx3iCOHTAibxP4UIEBC/QKIJEx3iCbMCFvEiCUMCBvEt7e3t7e3mwxMY6A3mxRaAP+JPhUgQEL9AuOgI6A4iBvE/hQgQEL9AqOJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/IIF8nJW8R+E+BAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3yt1VQTLB87Oy3/Lf5mXlARQIIIQGMjKZbrjAiCCECYm+cK64wIgghAnHWgkuuMCIIIQLGXZD7rjAnh2b2oDLjD4Qm7jAPpBldTR0PpA39HbPNs8f/hnoGudAv74SfhRgQEL9AogkTHe8uBt+CdvEGim/mChtX9y+wL4SSD4UYEBC/QLjoCOKI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHBwbwPi+E4hbxABbyIhpFUggCD0Fm8C+G74TyFvEAEkWYEBC/QS+G/4UCFvEAEjlWwD0FmBAQv0EvhwiCLIz4WIzo0EkEeGjAAAAAAAAAAAAAAAAAAAwM8WIc8UyXD7AIgjyM+FiM6NBJBHhowAAAAAAAAAAAAAAAAAAMDPFiHPFMlw+wAif29SMyP4USTbPMlZgQEL9BP4cV8Fbm2CAAhgGCIIAAgIcBydA8Yw+EJu4wD6QZXU0dD6QN/XDX+V1NHQ03/f1w1/ldTR0NN/39cNf5XU0dDTf9/R2zwhjigj0NMB+kAwMcjPhyDOjQQAAAAAAAAAAAAAAAAKcdaCSM8WygDJcPsAkTDi4wB/+GegcJ0D5nD4RSBukjBw3vhCuiCONjD4SfhNjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAExwWzIJYwIPhNxwXeMd/y4Gb4J28QghBZaC8AvvLgbvgAMHBTRPhUgQEL9AuOgI6A4iBvEfhQgQEL9AqZl3ECyo4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3/hRgQEL9AuOgI4ojQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEcHBvA+IhbxP4UIEBC/QKlXICvo4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3/hRgQEL9AuOgI4ojQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEcHBvA+IibxAglXMBwo5WMCJvEfhPgQEL9AogkTHeII5DMCJvE/hPgQEL9AogkTHeII4wMCJvEfhQgQEL9AogkTHeII4dMCJvE/hQgQEL9AogkTHeIJswIW8SIJQwIG8S3t7e3t7ebDExjoDebEF0A/wk+FSBAQv0C46AjoDiIG8T+FCBAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE38hUcEUlbxH4T4EBC/QKjiSNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATf+ChxVQTLB87Oy3+Zl3UAest/MSDJVHBzbxTIz5E6+/1Gzst/zMkjyM+FiM6NBJFloLwAAAAAAAAAAAAAAAAAAMDPFiHPFMlw+wBfBn8DaDD4Qm7jAPpBldTR0PpA3/pBldTR0PpA39cNf5XU0dDTf9/XDf+V1NHQ0//f0ds82zx/+Gegd50ALvgnbxBopv5gobV/cvsCXwR3+ElvAvhzA4ow+EJu4wD6QZXU0dD6QN/R2zwhjigj0NMB+kAwMcjPhyDOjQQAAAAAAAAAAAAAAAAJjIymWM8WygDJcPsAkTDi4wB/+GegeZ0C/HD4RSBukjBw3vhCuiCONjD4SfhNjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAExwWzIJYwIPhNxwXeMd/y4Gb4J28QghBZaC8AvvLgbvgAMHCIIsjPhYjOjQSRZaC8AAAAAAAAAAAAAAAAAADAzxYhzxTJcHt6AAr7AF8DfwAIcfx4MwRQIIIQDw5QirrjAiCCEBFl3ne64wIgghAVFrH4uuMCIIIQGIOlUrrjAoiGhH0DxjD4Qm7jAPpBldTR0PpA39cN/5XU0dDT/9/XDX+V1NHQ03/f1w1/ldTR0NN/39HbPCGOKCPQ0wH6QDAxyM+HIM6NBAAAAAAAAAAAAAAAAAmIOlUozxbKAMlw+wCRMOLbPH/4Z6B+nQH+cPhFIG6SMHDe+EK6II42MPhJ+E2NCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATHBbMgljAg+E3HBd4x3/LgZvgAIoIQO5rKAL4gjhYwIYIQstBeAL4gmjD4J28QXaC1f77e3vLgbzBwJPhPgQEL9AogkTHes38BGiCVMCP4UrzejoDebEGAA+ht+ELIy/9wWIBA9EMkyMv/cViAQPRD+ChyWIBA9BbI9ADJ+EzIz4SA9AD0AM+ByYhTEfkA+Cj6Qm8SyM+GQMoHy//J0AFTYcjPhYjOAfoCi9AAAAAAAAAAAAAAAAAHzxbMz4MizxTJcPsAIPhRgQEL9AuOgIOVgQHQjiiNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARwcG8D4ihvUCdvUXBvUiH4USLbPMlZgQEL9BP4cSjIz5C6I4sSzslTYsjPhYjOAfoCcc8LaiHPFMlw+wBfBiL4cn+CABJvIwLIzsv/ygAACGi1Xz8DgjD4Qm7jANHbPCKOLSTQ0wH6QDAxyM+HIM6AYs9AXgHPklRax+IBbyICyx/0AAFvIgLLH/QAyXD7AJFb4uMAf/hnoIWdAAj4VfhOA94w+EJu4wD6QZXU0dD6QN/XDX+V1NHQ03/f1w1/ldTR0NN/39cNf5XU0dDTf9/6QZXU0dD6QN/XDX+V1NHQ03/f1w1/ldTR0NN/39cNf5XU0dDTf9/6QZXU0dD6QN/XDX+V1NHQ03/f0ds82zx/+Gegh50ATvhJ+FSBAQv0CiCRMd7y4Gz4J28QaKb+YKG1f3L7Al8KefhJbwL4cwFSMNHbPPhQIY4cjQRwAAAAAAAAAAAAAAAAI8OUIqDIzvQAyXD7AN5/+GegBE4gggu3+zS64wIgghAG85DFuuMCIIIQB6fox7rjAiCCEAzjoOK64wKbjo2KA8Aw+EJu4wD6QZXU0dD6QN/6QZXU0dD6QN/6QZXU0dD6QN/6QZXU0dD6QN/R2zwhjigj0NMB+kAwMcjPhyDOjQQAAAAAAAAAAAAAAAAIzjoOKM8WygDJcPsAkTDi4wB/+Gegi50B6nD4RSBukjBw3vhCuiCONjD4SfhNjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAExwWzIJYwIPhNxwXeMd/y4Gb4J28QghBZaC8AvvLgbvgAMHBUcSPIz5As9vEKzlnIzgHIzs3NySXIz4WIzowARI0EkWWgvAAAAAAAAAAAAAAAAAAAwM8WIc8UyXD7AFt/bEEBUjDR2zz4VCGOHI0EcAAAAAAAAAAAAAAAACHp+jHgyM70AMlw+wDef/hnoAPYMPhCbuMA+kGV1NHQ+kDf+kGV1NHQ+kDf1w1/ldTR0NN/39cNf5XU0dDTf9/XDf+V1NHQ0//f0ds8IY4oI9DTAfpAMDHIz4cgzo0EAAAAAAAAAAAAAAAACG85DFjPFsoAyXD7AJEw4uMAf/hnoI+dA+Zw+EUgbpIwcN74QrogjjYw+En4TY0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMcFsyCWMCD4TccF3jHf8uBm+CdvEIIQWWgvAL7y4G74ADBwU0T4VIEBC/QLjoCOgOIgbxH4UIEBC/QKmZeQAsqOJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/4UYEBC/QLjoCOKI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHBwbwPiIW8T+FCBAQv0CpWRAr6OJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/4UYEBC/QLjoCOKI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHBwbwPiIm8QIJWSAcKOVjAibxH4T4EBC/QKIJEx3iCOQzAibxP4T4EBC/QKIJEx3iCOMDAibxH4UIEBC/QKIJEx3iCOHTAibxP4UIEBC/QKIJEx3iCbMCFvEiCUMCBvEt7e3t7e3mwxMY6A3mxRkwP+JPhUgQEL9AuOgI6A4iBvEfhQgQEL9AqOJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/IIF8nJW8T+E+BAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3yt0VQTLB87Oy3/Lf5mXlACAMSTIy/9czTIhyVRwisjPkTr7/UbOy3/MySTIz4WIzo0EkWWgvAAAAAAAAAAAAAAAAAAAwM8WIc8UyXD7AF8HfwEG0Ns8lgAS+kDT/9IA0W8DAdpwjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEmACUjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEbwYBBtDbPJoAVtIA+kD6QZXU0dD6QN/6QZXU0dD6QN/6QZXU0dD6QN/6QZXU0dD6QN/RbwYC9jD4Qm7jAPpBldTR0PpA3/pBldTR0PpA39cN/5XU0dDT/9/XDf+V1NHQ0//f1w3/ldTR0NP/39cN/5XU0dDT/98g10rAAZPU0dDe1CDXS8ABAcAAsJPU0dDe1NcNB5XU0dDTB9/XDX+V1NHQ03/f1w1/ldTR0NN/39cNf6CcAkaV1NHQ03/f1w1/ldTR0NN/39cNf5XU0dDTf9/R2zzjAH/4Z56dALD4VfhU+FP4UvhR+FD4T/hO+E34TPhL+Er4RvhD+ELIy//LP8oAzlWgyMv/zM4BbyICyx/0APQAVVDI9AD0AMv/AW8iAssHzvQAyFhvIgLLH/QAzc3Nye1UAf74RSBukjBw3vhCuvLga1MEciWotX+gtX9yJKi1f6C1fyWgtX+5syCaMCCCESoF8gC5s97y4Gr4J28QIbny0Gn4AFRxI1R3iVR971YTVhVWF1YZyM+RMfYqzs5VsMjOy/9VkMjL/8v/y//MzMsHy39VIMjLf8t/y3/Nzc3JIfhKnwAqyM+FiM4B+gJxzwtqIc8UyXH7AF8PALTtRNDT/9M/0gD6QNTR0NP/1PpA0x/0BFlvAgH0BNTR0PQE9ATT/9MH+kBZbwIB9ATU0dDTH/QEWW8CAdH4dfh0+HP4cvhx+HD4b/hu+G34bPhr+Gr4Zvhj+GICCvSkIPSho6IAFHNvbCAwLjQ3LjAAAA==",
		code: "te6ccgECoQEAMAQABCSK7VMg4wMgwP/jAiDA/uMC8gueAwGgAQACAv6NCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAT4aSHbPNMAAY4dgQIA1xgg+QEB0wABlNP/AwGTAvhC4iD4ZfkQ8qiV0wAB8nri0z8B+EMhufK0IPgjgQPoqIIIG3dAoLnytPhj0x8B+CO88rnTHwHbPPhHbvJ8QgQBaiLQ0wP6QDD4aak4APhEf29xggiYloBvcm1vc3BvdPhk3CHHANwh1w0f8rwh3QHbPPhHbvJ8BAM8IIIQNmc+qbvjAiCCEF4RYXG74wIgghBycMeDu+MCWx0FAiggghBtfd67u+MCIIIQcnDHg7vjAhYGAzwgghBwiI0fuuMCIIIQcQ2URrrjAiCCEHJwx4O64wITDwcDsjD4Qm7jAPpBldTR0PpA39cNf5XU0dDTf9/XDX+V1NHQ03/f0ds8IY4oI9DTAfpAMDHIz4cgzo0EAAAAAAAAAAAAAAAADycMeDjPFsoAyXD7AJEw4uMAf/hnnQiaA+pw+EUgbpIwcN74QrogjjYw+En4TY0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMcFsyCWMCD4TccF3jHf8uBm+CdvEIIQstBeALV/vvLgcfgAMHBTM/hUgQEL9AuOgI6A4iBvEfhQgQEL9AqWlAkCyo4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3/hRgQEL9AuOgI4ojQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEcHBvA+IhbxP4UIEBC/QKkgoCvo4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3/hRgQEL9AuOgI4ojQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEcHBvA+IibxAgkgsB6I5pMCJvEfhPgQEL9AogkTHeII5WMCJvE/hPgQEL9AogkTHeII5DMCJvFfhPgQEL9AogkTHeII4wMCJvEfhQgQEL9AogkTHeII4dMCJvE/hQgQEL9AogkTHeIJswIW8SIJQwIG8S3t7e3t7e3mwxMY6A3mwxDAP6I/hUgQEL9AuOgI6A4iBvEfhQgQEL9AqOJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN8hbxP4UIEBC/QKjiSNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATfyCByciZvFfhPgQEL9AqWlA0B/o4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3/goclUEywfOzst/y38xIMnIIHJyKG8V+E+BAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3/goclUEywfOzst/y38xIMlUcpYOANRvEsjPkTr7/UbOy3/MyVRxl28UyM+ROvv9Rs7Lf8zJJ8jPhYjOjQSRZaC8AAAAAAAAAAAAAAAAAADAzxYizxTJcPsAJsjPhYjOjQSRZaC8AAAAAAAAAAAAAAAAAADAzxYhzxTJcPsAXwp/A4ow+EJu4wD6QZXU0dD6QN/R2zwhjigj0NMB+kAwMcjPhyDOjQQAAAAAAAAAAAAAAAAPENlEaM8WygDJcPsAkTDi2zx/+GedEJoB1nD4RSBukjBw3vhCuiCONjD4SfhNjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAExwWzIJYwIPhNxwXeMd/y4Gb4J28QghBZaC8AvvLgbvgAMHAh+FSBAQv0CiCRMd6OgN8xEQSwIfhUgQEL9AuOgI6A4nBvUCL4VCLbPMlZgQEL9BP4dCL4VW8iIaRVIIAg9BZvAvh1iCPIz4WIzo0EkWWgvAAAAAAAAAAAAAAAAAAAwM8WIc8UyXD7AF8Df5aUJhIACGLFrusDnjD4Qm7jAPpBldTR0PpA39cNf5XU0dDTf9/R2zwhjigj0NMB+kAwMcjPhyDOjQQAAAAAAAAAAAAAAAAPCIjR+M8WygDJcPsAkTDi4wB/+GedFJoB2HD4RSBukjBw3vhCuiCONjD4SfhNjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAExwWzIJYwIPhNxwXeMd/y4Gb4J28QghBZaC8AvvLgbvgAMHAhyM+QYLq3sst/ySPIz4WIzhUARI0EkWWgvAAAAAAAAAAAAAAAAAAAwM8WIc8UyXD7AFt/bCEEUCCCEF7tOXa64wIgghBfC8/euuMCIIIQY1Nmp7rjAiCCEG193ru64wIbGhkXA0Aw+EJu4wD6QZXU0dD6QN/6QZXU0dD6QN/R2zzbPH/4Z50YmgAs+CdvEGim/mChtX9y+wJbePhJbwL4cwFSMNHbPPhPIY4cjQRwAAAAAAAAAAAAAAAAONTZqeDIzvQAyXD7AN5/+GedAVAw0ds8+E0hjhuNBHAAAAAAAAAAAAAAAAA3wvP3oMjOzslw+wDef/hnnQO2MPhCbuMA0wf6QZXU0dD6QN/6QZXU0dD6QN/6QZXU0dD6QN/XDQeV1NHQ0wff1w1/ldTR0NN/39cNf5XU0dDTf9/6QZXU0dD6QN/6QZXU0dD6QN/R2zzbPH/4Z50cmgAs+CdvEGim/mChtX9y+wJfCPhJbwL4cwRQIIIQRvJqSrvjAiCCEE3+ali74wIgghBTw/o6u+MCIIIQXhFhcbvjAkY7Jx4EUCCCEFT9xUi64wIgghBZQR+5uuMCIIIQWc+WpLrjAiCCEF4RYXG64wIkIiEfA44w+EJu4wD6QZXU0dD6QN/XDX+V1NHQ03/f+kGV1NHQ+kDf1w1/ldTR0NN/3/pBldTR0PpA39cNf5XU0dDTf9/R2zzbPH/4Z50gmgBO+En4VIEBC/QKIJEx3vLgbPgnbxBopv5gobV/cvsCXwZ6+ElvAvhzAVIw0ds8+FIhjhyNBHAAAAAAAAAAAAAAAAA2c+WpIMjOy//JcPsA3n/4Z50DtDD4Qm7jAPpBldTR0PpA3/pBldTR0PpA39cNf5XU0dDTf9/XDf+V1NHQ0//f+kGV1NHQ+kDf+kGV1NHQ+kDf+kGV1NHQ+kDf1w1/ldTR0NN/39TR2zzbPH/4Z50jmgAg+CdvEGim/mChtX9y+wJfCQN2MPhCbuMA+kGV1NHQ+kDf+kGV1NHQ+kDf+kGV1NHQ+kDf+kGV1NHQ+kDf+kGV1NHQ+kDf0ds82zx/+GedJZoDoPhJ+FSBAQv0CiCRMd7y4Gz4J28QaKb+YKG1f3L7AvhJIPhUgQEL9AuOgI6A4n9vUCZvUSVvUiRvUyNvVCJvVSH4VCLbPMlZgQEL9BP4dF8HlpQmADRvJl5AyMoAzlUwyM5VIMjOWcjOAcjOzc3NzQRQIIIQUGkGo7rjAiCCEFF/bKW64wIgghBR72U/uuMCIIIQU8P6OrrjAjYvLigD1jD4Qm7jAPpBldTR0PpA3/pBldTR0PpA3/pBldTR0PpA39cNf5XU0dDTf9/XDX+V1NHQ03/f0ds8IY4oI9DTAfpAMDHIz4cgzo0EAAAAAAAAAAAAAAAADTw/o6jPFsoAyXD7AJEw4uMAf/hnnSmaA+Zw+EUgbpIwcN74QrogjjYw+En4TY0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMcFsyCWMCD4TccF3jHf8uBm+CdvEIIQWWgvAL7y4G74ADBwU1X4VIEBC/QLjoCOgOIgbxH4UIEBC/QKlpQqAsqOJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/4UYEBC/QLjoCOKI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHBwbwPiIW8T+FCBAQv0CpIrAr6OJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/4UYEBC/QLjoCOKI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHBwbwPiIm8QIJIsAcKOVjAibxH4T4EBC/QKIJEx3iCOQzAibxP4T4EBC/QKIJEx3iCOMDAibxH4UIEBC/QKIJEx3iCOHTAibxP4UIEBC/QKIJEx3iCbMCFvEiCUMCBvEt7e3t7e3mwxMY6A3mxRLQP+JfhUgQEL9AuOgI6A4iBvE/hQgQEL9AqOJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/IIF8mJW8R+E+BAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3yt2VQTLB87Oy3/Lf5aUNQFQMNHbPPhKIY4bjQRwAAAAAAAAAAAAAAAANHvZT+DIzs7JcPsA3n/4Z50D1jD4Qm7jAPpBldTR0PpA3/pBldTR0PpA3/pBldTR0PpA39cNf5XU0dDTf9/XDX+V1NHQ03/f0ds8IY4oI9DTAfpAMDHIz4cgzo0EAAAAAAAAAAAAAAAADRf2yljPFsoAyXD7AJEw4uMAf/hnnTCaA+Zw+EUgbpIwcN74QrogjjYw+En4TY0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMcFsyCWMCD4TccF3jHf8uBm+CdvEIIQWWgvAL7y4G74ADBwU1X4VIEBC/QLjoCOgOIgbxH4UIEBC/QKlpQxAsqOJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/4UYEBC/QLjoCOKI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHBwbwPiIW8T+FCBAQv0CpIyAr6OJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/4UYEBC/QLjoCOKI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHBwbwPiIm8QIJIzAcKOVjAibxH4T4EBC/QKIJEx3iCOQzAibxP4T4EBC/QKIJEx3iCOMDAibxH4UIEBC/QKIJEx3iCOHTAibxP4UIEBC/QKIJEx3iCbMCFvEiCUMCBvEt7e3t7e3mwxMY6A3mxRNAP+JfhUgQEL9AuOgI6A4iBvEfhQgQEL9AqOJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/IIF8mJW8T+E+BAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3yt3VQTLB87Oy3/Lf5aUNQByMSDJVHBnyM+ROvv9Rs7Lf8zJI8jPhYjOjQSRZaC8AAAAAAAAAAAAAAAAAADAzxYhzxTJcPsAXwZ/A8Qw+EJu4wD6QZXU0dD6QN/6QZXU0dD6QN/XDX+V1NHQ03/f1w1/ldTR0NN/39HbPCGOKCPQ0wH6QDAxyM+HIM6NBAAAAAAAAAAAAAAAAA0GkGo4zxbKAMlw+wCRMOLjAH/4Z503mgG8cPhFIG6SMHDe+EK6II42MPhJ+E2NCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATHBbMgljAg+E3HBd4x3/LgZvgnbxAivvLgcvgAMHAk+FCBAQv0CjgBpI4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE340IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMcFjoDfbEE5Af4k+FCBAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE38ggdHQp+E+BAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3/godFUEywfOzst/y38xIMlUcFbIz5E6+/1Gzst/OgA0zMlTU8jPhYjOAfoCcc8LaiHPFMlw+wBfBX8EUCCCEEdWVNy64wIgghBJhZe6uuMCIIIQTO5kbLrjAiCCEE3+ali64wJAPz08AV4w0ds8+E4hjiKNBHAAAAAAAAAAAAAAAAAzf5qWIMjOAW8iAssf9ADJcPsA3n/4Z50DbDD4Qm7jAPpBldTR0PpA39cNf5XU0dDTf9/XDACV1NHQ0gDf1w0HldTR0NMH39TR2zzjAH/4Z50+mgDg+EUgbpIwcN74QrogjjYw+En4TY0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMcFsyCWMCD4TccF3jHf8uBm+CdvECS+8uBz+ABUc0LIz4WAygBzz0DOAfoCcc8LaiHPFMki+wBfBQFcMNHbPPhTIY4hjQRwAAAAAAAAAAAAAAAAMmFl7qDIzgFvIgLLB87JcPsA3n/4Z50CxDD4Qm7jAPhG8nN/+Gb6QZXU0dD6QN/R+En4SscFjkP4J28QghA7msoAoLV/aKb+YKG1f3L7Al8g+G34KPhCyM+Q6BWtjsv/zgHIzs3J+ErIz4WIznHPC24hzxTJgQCA+wAwQkEB1o5i+ACNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQg+G34KPhCyM+Q6BWtjsv/zgHIzs3J+ErIz4WIzo0EkHc1lAAAAAAAAAAAAAAAAAAAwM8WIc8UyXD7ADDiMNs8f/hnmgIW7UTQ10nCAYqOgOKdQwL+cO1E0PQFcSGAQPQOjiSNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATf+GpyIYBA9A6T1wv/kXDi+GtzIYBA9A+OgN/4bI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABPhtcG1vAvhubfhvbUVEAJb4cG34cXD4cnCNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARvAvhzbfh0cG1vAvh1gED0DvK91wv/+GJw+GNw+GYBAoigBFAgghA8FwBhuuMCIIIQRDh4CrrjAiCCEEVETxq64wIgghBG8mpKuuMCV1BJRwPyMPhCbuMA0x/4RFhvdfhk1w3/ldTR0NP/39HbPCGOHyPQ0wH6QDAxyM+HIM5xzwthAcjPkxvJqSrOzclw+wCOM/hEIG8TIW8S+ElVAm8RyHLPQMoAc89AzgH6AvQAcc8LaQHI+ERvFc8LH87NyfhEbxT7AOLjAH/4Z51ImgCW+ERwb3Jwb3GAQG90+GQgbfhCyMv/cFiAQPRDIcjL/3FYgED0Q/gocliAQPQWyPQAyfhMyM+EgPQA9ADPgcn5AMjPigBAy//J0DExA8Yw+EJu4wD6QZXU0dD6QN/XDX+V1NHQ03/f1w1/ldTR0NN/39cNf5XU0dDTf9/R2zwhjigj0NMB+kAwMcjPhyDOjQQAAAAAAAAAAAAAAAAMVETxqM8WygDJcPsAkTDi4wB/+GedSpoD5nD4RSBukjBw3vhCuiCONjD4SfhNjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAExwWzIJYwIPhNxwXeMd/y4Gb4J28QghBZaC8AvvLgbvgAMHBTRPhUgQEL9AuOgI6A4iBvEfhQgQEL9AqWlEsCyo4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3/hRgQEL9AuOgI4ojQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEcHBvA+IhbxP4UIEBC/QKkkwCvo4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3/hRgQEL9AuOgI4ojQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEcHBvA+IibxAgkk0Bwo5WMCJvEfhPgQEL9AogkTHeII5DMCJvE/hPgQEL9AogkTHeII4wMCJvEfhQgQEL9AogkTHeII4dMCJvE/hQgQEL9AogkTHeIJswIW8SIJQwIG8S3t7e3t7ebDExjoDebEFOA/wk+FSBAQv0C46AjoDiIG8R+FCBAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE38hUcEUlbxP4T4EBC/QKjiSNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATf+ChxVQTLB87Oy3+WlE8Aest/MSDJVHBzbxLIz5E6+/1Gzst/zMkjyM+FiM6NBJFloLwAAAAAAAAAAAAAAAAAAMDPFiHPFMlw+wBfBn8DnjD4Qm7jAPpBldTR0PpA39cNf5XU0dDTf9/R2zwhjigj0NMB+kAwMcjPhyDOjQQAAAAAAAAAAAAAAAAMQ4eAqM8WygDJcPsAkTDi4wB/+GedUZoD5nD4RSBukjBw3vhCuiCONjD4SfhNjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAExwWzIJYwIPhNxwXeMd/y4Gb4J28QghBZaC8AvvLgbvgAMHBTIvhUgQEL9AuOgI6A4iBvEfhQgQEL9AqWlFICyo4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3/hRgQEL9AuOgI4ojQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEcHBvA+IhbxP4UIEBC/QKklMCvo4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3/hRgQEL9AuOgI4ojQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEcHBvA+IibxAgklQB6I5pMCJvEfhPgQEL9AogkTHeII5WMCJvE/hPgQEL9AogkTHeII5DMCJvFfhPgQEL9AogkTHeII4wMCJvEfhQgQEL9AogkTHeII4dMCJvE/hQgQEL9AogkTHeIJswIW8SIJQwIG8S3t7e3t7e3mwxMY6A3mwhVQP+IvhUgQEL9AuOgI6A4sggc3MkbxP4T4EBC/QKjiSNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATfJW8R+E+BAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE33NVBMsHzs7Lf8t/MZaUVgDQIMkgXybIz5G0qjiOy3/OzMkjbxX4UIEBC/QKjiSNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATfyM+FiM6NBJFloLwAAAAAAAAAAAAAAAAAAMDPFiHPFMlw+wBfBX8DsjD4Qm7jAPpBldTR0PpA39HbPCeOOynQ0wH6QDAxyM+HIM5xzwthXlFVYMjPkvBcAYbKAM5VQMjOVTDIzlUgyM5ZyM4ByM7Nzc3Nzc3JcPsAkl8H4uMAf/hnnViaAdpwjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEWQP8jQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEJ/hUgQEL9AuOgI6A4iBvEDgglpRaACxvETcgbxI2IG8TNSBvFDRvFTIwJmwXBFAgghAM46Diu+MCIIIQGIOlUrvjAiCCECxl2Q+74wIgghA2Zz6pu+MChnlmXARQIIIQLjVeOrrjAiCCEDKmhOG64wIgghAzNqVSuuMCIIIQNmc+qbrjAmBfXl0BXjDR2zz4VSGOIo0EcAAAAAAAAAAAAAAAAC2Zz6pgyM4BbyICyx/0AMlw+wDef/hnnQFSMNHbPPhLIY4cjQRwAAAAAAAAAAAAAAAALM2pVKDIzsv/yXD7AN5/+GedAVAw0ds8+EwhjhuNBHAAAAAAAAAAAAAAAAAsqaE4YMjOzMlw+wDef/hnnQPYMPhCbuMA+kGV1NHQ+kDf+kGV1NHQ+kDf1w1/ldTR0NN/39cNf5XU0dDTf9/XDf+V1NHQ0//f0ds8IY4oI9DTAfpAMDHIz4cgzo0EAAAAAAAAAAAAAAAACuNV46jPFsoAyXD7AJEw4uMAf/hnnWGaA+Zw+EUgbpIwcN74QrogjjYw+En4TY0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMcFsyCWMCD4TccF3jHf8uBm+CdvEIIQWWgvAL7y4G74ADBwU0T4VIEBC/QLjoCOgOIgbxH4UIEBC/QKlpRiAsqOJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/4UYEBC/QLjoCOKI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHBwbwPiIW8T+FCBAQv0CpJjAr6OJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/4UYEBC/QLjoCOKI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHBwbwPiIm8QIJJkAcKOVjAibxH4T4EBC/QKIJEx3iCOQzAibxP4T4EBC/QKIJEx3iCOMDAibxH4UIEBC/QKIJEx3iCOHTAibxP4UIEBC/QKIJEx3iCbMCFvEiCUMCBvEt7e3t7e3mwxMY6A3mxRZQP+JPhUgQEL9AuOgI6A4iBvE/hQgQEL9AqOJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/IIF8nJW8R+E+BAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3yt1VQTLB87Oy3/Lf5aUkQRQIIIQGMjKZbrjAiCCECYm+cK64wIgghAnHWgkuuMCIIIQLGXZD7rjAnVzbGcDLjD4Qm7jAPpBldTR0PpA39HbPNs8f/hnnWiaAv74SfhRgQEL9AogkTHe8uBt+CdvEGim/mChtX9y+wL4SSD4UYEBC/QLjoCOKI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHBwbwPi+E4hbxABbyIhpFUggCD0Fm8C+G74TyFvEAEkWYEBC/QS+G/4UCFvEAEjkmkD0FmBAQv0EvhwiCLIz4WIzo0EkEeGjAAAAAAAAAAAAAAAAAAAwM8WIc8UyXD7AIgjyM+FiM6NBJBHhowAAAAAAAAAAAAAAAAAAMDPFiHPFMlw+wAif29SMyP4USTbPMlZgQEL9BP4cV8Fa2p/AAhgGCIIAAgIcBydA8Yw+EJu4wD6QZXU0dD6QN/XDX+V1NHQ03/f1w1/ldTR0NN/39cNf5XU0dDTf9/R2zwhjigj0NMB+kAwMcjPhyDOjQQAAAAAAAAAAAAAAAAKcdaCSM8WygDJcPsAkTDi4wB/+GedbZoD5nD4RSBukjBw3vhCuiCONjD4SfhNjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAExwWzIJYwIPhNxwXeMd/y4Gb4J28QghBZaC8AvvLgbvgAMHBTRPhUgQEL9AuOgI6A4iBvEfhQgQEL9AqWlG4Cyo4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3/hRgQEL9AuOgI4ojQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEcHBvA+IhbxP4UIEBC/QKkm8Cvo4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3/hRgQEL9AuOgI4ojQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEcHBvA+IibxAgknABwo5WMCJvEfhPgQEL9AogkTHeII5DMCJvE/hPgQEL9AogkTHeII4wMCJvEfhQgQEL9AogkTHeII4dMCJvE/hQgQEL9AogkTHeIJswIW8SIJQwIG8S3t7e3t7ebDExjoDebEFxA/wk+FSBAQv0C46AjoDiIG8T+FCBAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE38hUcEUlbxH4T4EBC/QKjiSNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATf+ChxVQTLB87Oy3+WlHIAest/MSDJVHBzbxTIz5E6+/1Gzst/zMkjyM+FiM6NBJFloLwAAAAAAAAAAAAAAAAAAMDPFiHPFMlw+wBfBn8DaDD4Qm7jAPpBldTR0PpA3/pBldTR0PpA39cNf5XU0dDTf9/XDf+V1NHQ0//f0ds82zx/+GeddJoALvgnbxBopv5gobV/cvsCXwR3+ElvAvhzA4ow+EJu4wD6QZXU0dD6QN/R2zwhjigj0NMB+kAwMcjPhyDOjQQAAAAAAAAAAAAAAAAJjIymWM8WygDJcPsAkTDi4wB/+GeddpoC/HD4RSBukjBw3vhCuiCONjD4SfhNjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAExwWzIJYwIPhNxwXeMd/y4Gb4J28QghBZaC8AvvLgbvgAMHCIIsjPhYjOjQSRZaC8AAAAAAAAAAAAAAAAAADAzxYhzxTJcHh3AAr7AF8DfwAIcfx4MwRQIIIQDw5QirrjAiCCEBFl3ne64wIgghAVFrH4uuMCIIIQGIOlUrrjAoWDgXoDxjD4Qm7jAPpBldTR0PpA39cN/5XU0dDT/9/XDX+V1NHQ03/f1w1/ldTR0NN/39HbPCGOKCPQ0wH6QDAxyM+HIM6NBAAAAAAAAAAAAAAAAAmIOlUozxbKAMlw+wCRMOLbPH/4Z517mgH+cPhFIG6SMHDe+EK6II42MPhJ+E2NCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATHBbMgljAg+E3HBd4x3/LgZvgAIoIQO5rKAL4gjhYwIYIQstBeAL4gmjD4J28QXaC1f77e3vLgbzBwJPhPgQEL9AogkTHes3wBGiCVMCP4UrzejoDebEF9A+ht+ELIy/9wWIBA9EMkyMv/cViAQPRD+ChyWIBA9BbI9ADJ+EzIz4SA9AD0AM+ByYhTEfkA+Cj6Qm8SyM+GQMoHy//J0AFTYcjPhYjOAfoCi9AAAAAAAAAAAAAAAAAHzxbMz4MizxTJcPsAIPhRgQEL9AuOgICSfgHQjiiNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARwcG8D4ihvUCdvUXBvUiH4USLbPMlZgQEL9BP4cSjIz5C6I4sSzslTYsjPhYjOAfoCcc8LaiHPFMlw+wBfBiL4cn9/ABJvIwLIzsv/ygAACGi1Xz8DgjD4Qm7jANHbPCKOLSTQ0wH6QDAxyM+HIM6AYs9AXgHPklRax+IBbyICyx/0AAFvIgLLH/QAyXD7AJFb4uMAf/hnnYKaAAj4VfhOA94w+EJu4wD6QZXU0dD6QN/XDX+V1NHQ03/f1w1/ldTR0NN/39cNf5XU0dDTf9/6QZXU0dD6QN/XDX+V1NHQ03/f1w1/ldTR0NN/39cNf5XU0dDTf9/6QZXU0dD6QN/XDX+V1NHQ03/f0ds82zx/+GedhJoATvhJ+FSBAQv0CiCRMd7y4Gz4J28QaKb+YKG1f3L7Al8KefhJbwL4cwFSMNHbPPhQIY4cjQRwAAAAAAAAAAAAAAAAI8OUIqDIzvQAyXD7AN5/+GedBE4gggu3+zS64wIgghAG85DFuuMCIIIQB6fox7rjAiCCEAzjoOK64wKYi4qHA8Aw+EJu4wD6QZXU0dD6QN/6QZXU0dD6QN/6QZXU0dD6QN/6QZXU0dD6QN/R2zwhjigj0NMB+kAwMcjPhyDOjQQAAAAAAAAAAAAAAAAIzjoOKM8WygDJcPsAkTDi4wB/+GediJoB6nD4RSBukjBw3vhCuiCONjD4SfhNjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAExwWzIJYwIPhNxwXeMd/y4Gb4J28QghBZaC8AvvLgbvgAMHBUcSPIz5As9vEKzlnIzgHIzs3NySXIz4WIzokARI0EkWWgvAAAAAAAAAAAAAAAAAAAwM8WIc8UyXD7AFt/bEEBUjDR2zz4VCGOHI0EcAAAAAAAAAAAAAAAACHp+jHgyM70AMlw+wDef/hnnQPYMPhCbuMA+kGV1NHQ+kDf+kGV1NHQ+kDf1w1/ldTR0NN/39cNf5XU0dDTf9/XDf+V1NHQ0//f0ds8IY4oI9DTAfpAMDHIz4cgzo0EAAAAAAAAAAAAAAAACG85DFjPFsoAyXD7AJEw4uMAf/hnnYyaA+Zw+EUgbpIwcN74QrogjjYw+En4TY0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMcFsyCWMCD4TccF3jHf8uBm+CdvEIIQWWgvAL7y4G74ADBwU0T4VIEBC/QLjoCOgOIgbxH4UIEBC/QKlpSNAsqOJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/4UYEBC/QLjoCOKI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHBwbwPiIW8T+FCBAQv0CpKOAr6OJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/4UYEBC/QLjoCOKI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHBwbwPiIm8QIJKPAcKOVjAibxH4T4EBC/QKIJEx3iCOQzAibxP4T4EBC/QKIJEx3iCOMDAibxH4UIEBC/QKIJEx3iCOHTAibxP4UIEBC/QKIJEx3iCbMCFvEiCUMCBvEt7e3t7e3mwxMY6A3mxRkAP+JPhUgQEL9AuOgI6A4iBvEfhQgQEL9AqOJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/IIF8nJW8T+E+BAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3yt0VQTLB87Oy3/Lf5aUkQCAMSTIy/9czTIhyVRwisjPkTr7/UbOy3/MySTIz4WIzo0EkWWgvAAAAAAAAAAAAAAAAAAAwM8WIc8UyXD7AF8HfwEG0Ns8kwAS+kDT/9IA0W8DAdpwjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAElQCUjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEbwYBBtDbPJcAVtIA+kD6QZXU0dD6QN/6QZXU0dD6QN/6QZXU0dD6QN/6QZXU0dD6QN/RbwYC9jD4Qm7jAPpBldTR0PpA3/pBldTR0PpA39cN/5XU0dDT/9/XDf+V1NHQ0//f1w3/ldTR0NP/39cN/5XU0dDT/98g10rAAZPU0dDe1CDXS8ABAcAAsJPU0dDe1NcNB5XU0dDTB9/XDX+V1NHQ03/f1w1/ldTR0NN/39cNf52ZAkaV1NHQ03/f1w1/ldTR0NN/39cNf5XU0dDTf9/R2zzjAH/4Z5uaALD4VfhU+FP4UvhR+FD4T/hO+E34TPhL+Er4RvhD+ELIy//LP8oAzlWgyMv/zM4BbyICyx/0APQAVVDI9AD0AMv/AW8iAssHzvQAyFhvIgLLH/QAzc3Nye1UAf74RSBukjBw3vhCuvLga1MEciWotX+gtX9yJKi1f6C1fyWgtX+5syCaMCCCESoF8gC5s97y4Gr4J28QIbny0Gn4AFRxI1R3iVR971YTVhVWF1YZyM+RMfYqzs5VsMjOy/9VkMjL/8v/y//MzMsHy39VIMjLf8t/y3/Nzc3JIfhKnAAqyM+FiM4B+gJxzwtqIc8UyXH7AF8PALTtRNDT/9M/0gD6QNTR0NP/1PpA0x/0BFlvAgH0BNTR0PQE9ATT/9MH+kBZbwIB9ATU0dDTH/QEWW8CAdH4dfh0+HP4cvhx+HD4b/hu+G34bPhr+Gr4Zvhj+GICCvSkIPShoJ8AFHNvbCAwLjQ3LjAAAA==",
	},
};
