// app
export const CHANGE_THEME = "CHANGE_THEME";

export const SET_EXTENSIONS_LIST = "SET_EXTENSIONS_LIST";
export const SET_CUR_EXT = "SET_CUR_EXT";

export const CONNECT_WALLET = "CONNECT_WALLET";
export const CLOSE_CONNECTING = "CLOSE_CONNECTING";

export const SET_WALLET_IS_CONNECTED = "SET_WALLET_IS_CONNECTED";

export const SHOW_ACCOUNT = "SHOW_ACCOUNT";
export const HIDE_ACCOUNT = "HIDE_ACCOUNT";

export const SHOW_POPUP = "SHOW_POPUP";
export const HIDE_POPUP = "HIDE_POPUP";

export const SHOW_TIP = "SHOW_TIP";
export const HIDE_TIP = "HIDE_TIP";
export const CHANGE_TIP_TEXT = "CHANGE_TIP_TEXT";
export const CHANGE_TIP_DURATION = "CHANGE_TIP_DURATION";
export const CHANGE_TIP_SEVERITY = "CHANGE_TIP_SEVERITY";
export const SET_SUBSCRIBE_RECEIVE_TOKENS = "SET_SUBSCRIBE_RECEIVE_TOKENS";
export const SET_ACCEPTED_PAIR_TOKENS = "SET_ACCEPTED_PAIR_TOKENS";
export const SET_TIPS = "SET_TIPS";

// walletSeed

export const SET_SEND_AMOUNT = "SET_SEND_AMOUNT";
export const SET_SEND_ADDRESS = "SET_SEND_ADDRESS";
export const SET_SEND_TOKEN = "SET_SEND_TOKEN";
export const SET_TOKEN_SETTED = "SET_TOKEN_SETTED";
export const SET_SHOW_ASSETS_FOR_SEND = "SET_SHOW_ASSETS_FOR_SEND";
export const SET_RECEIVE_TOKEN = "SET_RECEIVE_TOKEN";
export const SET_RECEIVE_TOKEN_SETTED = "SET_RECEIVE_TOKEN_SETTED";
export const SET_SHOW_WAITING_SEND_ASSET_POPUP =
	"SET_SHOW_WAITING_SEND_ASSET_POPUP";

// wallet
export const SET_WALLET = "SET_WALLET";
export const SET_CLIENT_DATA = "SET_CLIENT_DATA";
export const SET_TOKEN_LIST = "SET_TOKEN_LIST";
export const SET_PAIRS_LIST = "SET_PAIRS_LIST";
export const SET_LIQUIDITY_LIST = "SET_LIQUIDITY_LIST";
export const SET_TRANSACTIONS_LIST = "SET_TRANSACTIONS_LIST";
export const SET_SUBSCRIBE_DATA = "SET_SUBSCRIBE_DATA";
export const SET_NFT_ASSETS = "SET_NFT_ASSETS";
export const SET_INPUT_NFT_DISABLED = "SET_INPUT_NFT_DISABLED";
export const SET_UPDATED_BALANCE = "SET_UPDATED_BALANCE";
export const SET_ASSET_LIST_FOR_DEPLOY = "SET_ASSET_LIST_FOR_DEPLOY";

// Stacking

export const SHOW_STACKING_CONFIRM_POPUP = "SHOW_STACKING_CONFIRM_POPUP";
export const HIDE_STACKING_CONFIRM_POPUP = "HIDE_STACKING_CONFIRM_POPUP";
export const SET_APY_FOR_STACKING = "SET_APY_FOR_STACKING";
export const SET_AMOUNT_FOR_STACkING = "SET_AMOUNT_FOR_STACkING";
export const SET_PERIOD_FOR_STACkING = "SET_PERIOD_FOR_STACkING";
export const SET_SHOW_STAKING_WAITING_POPUP = "SET_SHOW_STAKING_WAITING_POPUP";

// Client wallets
export const SHOW_CLIENT_WALLETS_FROM_SELECT =
	"SHOW_CLIENT_WALLETS_FROM_SELECT";
export const HIDE_CLIENT_WALLETS_FROM_SELECT =
	"HIDE_CLIENT_WALLETS_FROM_SELECT";

// Pool explorer
export const SHOW_POOL_EXPLORER = "SHOW_POOL_EXPLORER";
export const HIDE_POOL_EXPLORER = "HIDE_POOL_EXPLORER";

// Enter seed phrase
export const SHOW_ENTER_SEED_PHRASE = "SHOW_ENTER_SEED_PHRASE";
// export const HIDE_ENTER_SEED_PHRASE = 'HIDE_ENTER_SEED_PHRASE';
export const SET_PASSWORD = "SET_PASSWORD";

export const ENTER_SEED_PHRASE_SIDE = "ENTER_SEED_PHRASE_SIDE";
export const ENTER_ENCRYPTED_SEED_PHRASE = "ENTER_ENCRYPTED_SEED_PHRASE";

export const ENTER_SEED_PHRASE_WORD_ONE = "ENTER_SEED_PHRASE_WORD_ONE";
export const ENTER_SEED_PHRASE_WORD_TWO = "ENTER_SEED_PHRASE_WORD_TWO";
export const ENTER_SEED_PHRASE_WORD_THREE = "ENTER_SEED_PHRASE_WORD_THREE";
export const ENTER_SEED_PHRASE_WORD_FOUR = "ENTER_SEED_PHRASE_WORD_FOUR";
export const ENTER_SEED_PHRASE_WORD_FIVE = "ENTER_SEED_PHRASE_WORD_FIVE";
export const ENTER_SEED_PHRASE_WORD_SIX = "ENTER_SEED_PHRASE_WORD_SIX";
export const ENTER_SEED_PHRASE_WORD_SEVEN = "ENTER_SEED_PHRASE_WORD_SEVEN";
export const ENTER_SEED_PHRASE_WORD_EIGHT = "ENTER_SEED_PHRASE_WORD_EIGHT";
export const ENTER_SEED_PHRASE_WORD_NINE = "ENTER_SEED_PHRASE_WORD_NINE";
export const ENTER_SEED_PHRASE_WORD_TEN = "ENTER_SEED_PHRASE_WORD_TEN";
export const ENTER_SEED_PHRASE_WORD_ELEVEN = "ENTER_SEED_PHRASE_WORD_ELEVEN";
export const ENTER_SEED_PHRASE_WORD_TWELVE = "ENTER_SEED_PHRASE_WORD_TWELVE";

export const ENTER_SEED_PHRASE_UNLOCK_SHOW = "ENTER_SEED_PHRASE_UNLOCK_SHOW";
export const ENTER_SEED_PHRASE_UNLOCK_HIDE = "ENTER_SEED_PHRASE_UNLOCK_HIDE";

export const ENTER_SEED_PHRASE_REGISTER_SHOW =
	"ENTER_SEED_PHRASE_REGISTER_SHOW";
export const ENTER_SEED_PHRASE_REGISTER_HIDE =
	"ENTER_SEED_PHRASE_REGISTER_HIDE";

export const ENTER_SEED_PHRASE_EMPTY_STORAGE =
	"ENTER_SEED_PHRASE_EMPTY_STORAGE";
export const HIDE_REVEAL_SEED_PHRASE = "HIDE_REVEAL_SEED_PHRASE";
export const SHOW_REVEAL_SEED_PHRASE = "SHOW_REVEAL_SEED_PHRASE";

export const ENTER_SEED_PHRASE_SAVE_TO_LOCAL_STORAGE =
	"ENTER_SEED_PHRASE_SAVE_TO_LOCAL_STORAGE";

export const SET_TIP = "SET_TIP";

// Limit orders
export const SHOW_ORDERS_FROM_SELECT = "SHOW_ORDERS_FROM_SELECT";
export const HIDE_ORDERS_FROM_SELECT = "HIDE_ORDERS_FROM_SELECT";

export const SHOW_ORDERS_TO_SELECT = "SHOW_ORDERS_TO_SELECT";
export const HIDE_ORDERS_TO_SELECT = "HIDE_ORDERS_TO_SELECT";

export const SHOW_ORDERS_CONFIRM_POPUP = "SHOW_ORDERS_CONFIRM_POPUP";
export const HIDE_ORDERS_CONFIRM_POPUP = "HIDE_ORDERS_CONFIRM_POPUP";

export const SET_ORDERS_FROM_INPUT_VALUE = "SET_ORDERS_FROM_INPUT_VALUE";
export const SET_ORDERS_TO_INPUT_VALUE = "SET_ORDERS_TO_INPUT_VALUE";

export const SET_ORDERS_FROM_TOKEN = "SET_ORDERS_FROM_TOKEN";
export const SET_ORDERS_TO_TOKEN = "SET_ORDERS_TO_TOKEN";

export const SET_ORDERS_PAIR_ID = "SET_ORDERS_PAIR_ID";
export const SET_ORDERS_RATE = "SET_ORDERS_RATE";
export const SET_ORDERS_ASYNC_IS_WAITING = "SET_ORDERS_ASYNC_IS_WAITING";
export const SET_ORDER_LIST = "SET_ORDER_LIST";
export const SET_ORDER_LIST_LOADING = "SET_ORDER_LIST_LOADING";
export const SET_ORDER_LIST_FETCHED = "SET_ORDER_LIST_FETCHED";

// swap
export const SHOW_SWAP_FROM_SELECT = "SHOW_SWAP_FROM_SELECT";
export const HIDE_SWAP_FROM_SELECT = "HIDE_SWAP_FROM_SELECT";

export const SHOW_SWAP_TO_SELECT = "SHOW_SWAP_TO_SELECT";
export const HIDE_SWAP_TO_SELECT = "HIDE_SWAP_TO_SELECT";

export const SET_SWAP_FROM_INPUT_VALUE = "SET_SWAP_FROM_INPUT_VALUE";
export const SET_SWAP_TO_INPUT_VALUE = "SET_SWAP_TO_INPUT_VALUE";

export const SET_SWAP_FROM_TOKEN = "SET_SWAP_FROM_TOKEN";
export const SET_SWAP_TO_TOKEN = "SET_SWAP_TO_TOKEN";

export const SET_SWAP_PAIR_ID = "SET_SWAP_PAIR_ID";

export const SET_SWAP_ASYNC_IS_WAITING = "SET_SWAP_ASYNC_IS_WAITING";

export const SET_SWAP_RATE = "SET_SWAP_RATE";
export const SET_SWAP_FROM_INPUT_VALUE_CHANGE =
	"SET_SWAP_FROM_INPUT_VALUE_CHANGE";
export const SET_SLIPPAGE = "SET_SLIPPAGE";

// pool
export const SHOW_POOL_FROM_SELECT = "SHOW_POOL_FROM_SELECT";
export const HIDE_POOL_FROM_SELECT = "HIDE_POOL_FROM_SELECT";

export const SHOW_POOL_TO_SELECT = "SHOW_POOL_TO_SELECT";
export const HIDE_POOL_TO_SELECT = "HIDE_POOL_TO_SELECT";

export const SET_POOL_FROM_INPUT_VALUE = "SET_POOL_FROM_INPUT_VALUE";
export const SET_POOL_TO_INPUT_VALUE = "SET_POOL_TO_INPUT_VALUE";

export const SET_POOL_FROM_TOKEN = "SET_POOL_FROM_TOKEN";
export const SET_POOL_TO_TOKEN = "SET_POOL_TO_TOKEN";

export const SET_POOL_PAIR_ID = "SET_POOL_PAIR_ID";

export const SET_POOL_ASYNC_IS_WAITING = "SET_POOL_ASYNC_IS_WAITING";

export const SET_POOL_RATE = "SET_POOL_RATE";

//  manage
export const SET_MANAGE_FROM_TOKEN = "SET_MANAGE_FROM_TOKEN";
export const SET_MANAGE_TO_TOKEN = "SET_MANAGE_TO_TOKEN";

export const SET_MANAGE_RATE_AB = "SET_MANAGE_RATE_AB";
export const SET_MANAGE_RATE_BA = "SET_MANAGE_RATE_BA";

export const SET_MANAGE_PAIR_ID = "SET_MANAGE_PAIR_ID";

export const SET_MANAGE_BALANCE = "SET_MANAGE_BALANCE";

export const SET_MANAGE_ASYNC_IS_WAITING = "SET_MANAGE_ASYNC_IS_WAITING";
